#!/usr/bin/env bash
# Copyright (c) 2026, Neil Aldea <njaldea@gmail.com>
# SPDX-License-Identifier: BSL-1.0

if [[ $0 != $BASH_SOURCE ]]; then
    echo "do not source this script"
    return 1
fi

SCRIPT_PATH=`(dirname $BASH_SOURCE)`
REPO_PATH=`(realpath $SCRIPT_PATH/..)`
cd $REPO_PATH

CMAKE_BUILD_TYPE="Release"
VCPKG_MANIFEST_FEATURES="core"
GENERATOR="Ninja"

export VCPKG_BINARY_SOURCES="default"
export CMAKE_BUILD_PARALLEL_LEVEL=8

cmake                                                                       \
    -B "${REPO_PATH}/.build"                                                \
    -DCMAKE_INSTALL_PREFIX="${REPO_PATH}/.build/out"                        \
    -G "${GENERATOR}"
